# Generated by Django 6.0.6 on 2026-06-21 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price_at_order',
        ),
    ]
